Elorus API client for python
withlogicco/elorus-python-sdk pull request #1
Opened 2024-05-21 09:51 UTC by phemmylintry

2024-05-21 10:29 UTC, parisk requested changes
Great kick off! Let's move on with full functionality for contacts and invoices. Created issue at https://github.com/withlogicco/elorus-python-sdk/issues/2

2024-05-28 06:07 UTC, akalipetis reviewed
Let's see if we can ditch the `serialize` function, as proposed in #4

2024-05-28 06:07 UTC, akalipetis commented on .devcontainer/devcontainer.json
> +    "postCreateCommand": "poetry install",
```suggestion
```

We don't need this one, since the Docker image already has the Poetry dependencies.

2024-05-28 06:07 UTC, akalipetis commented on .devcontainer/devcontainer.json
> +    ],
This should be created, it currently does not exist.

2024-05-30 10:13 UTC, akalipetis reviewed
LGTM 🐻

2024-05-30 10:13 UTC, akalipetis approved these changes, later dismissed

2024-05-30 10:25 UTC, parisk requested changes
Great work! Just a small update and we should be good to go.

2024-05-30 10:25 UTC, parisk commented on elorus/client.py
> +        return filename, response.content
I suggest we simplify this a bit and also use better naming. Example:

```suggestion
        content_disposition = response.headers.get("Content-Disposition", "")
        filename_kv = filename.split("filename=")
        if len(filename_kv) >= 2:
            filename = filename_kv.split("filename=")[1]
            return filename, response.content
```

2024-05-30 12:20 UTC, parisk approved these changes
LGTM 🦛

2024-05-30 12:21 UTC, merged